### PR TITLE
Add: cart page

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
- added cart page
- cart page is responsive as well

### CODE REVIEW

**Review by varnita619 — APPROVED** [review]
good use of meta tags.

**Review by Hnh013 — APPROVED** [review]
Loved the design, good to merge!

**Review by varnita619 — APPROVED** [review]

**Comment by inductionotg** [comment]
looks good

**Review by SadiqZak — COMMENTED** [review]
Yup, looks good to me as well

**Pull request merged**
