### PR TITLE
Add: structure , login page

### PR DESCRIPTION
**Pull request by SJTGSHIVAM**
- added complete structure of the project
- added boiler plate code everywhere
- added login page

### CODE REVIEW

**Review by varnita619 — APPROVED** [review]
Looks good to merge

**Review by palash23jain — APPROVED** [review]
good practice of using svgs and webp files. nice use of grid area for layouting. looks good to me.

**Review by romabulani — APPROVED** [review]
Looks good to merge

**Review by Hnh013 — APPROVED** [review]
Looks good to merge!

**Pull request merged**
